import Head from 'next/head';
import Application from '../components/Application';
import Graduates from '../components/Graduates';

import Hero from '../components/Hero';

import Success from '../components/Success';
import Trainee from '../components/Trainee';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Algorizin</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Hero />
        <Success />
        <Graduates />
        <Trainee />
        <Application />
      </main>
    </div>
  );
}
